# docker-compose.prod.yml (Production specific configuration)
name: lapbee_production

services:
  # === Backend Service (Node.js) ===
  backend:
    image: nguyenminhtri1808t/lapbee_ecommerce_backend:latest
    env_file: '.env.prod'
    ports:
      - '8080:${PORT}'
    depends_on:
      - mongodb
      - redis
    restart: always

  # === MongoDB Service ===
  mongodb:
    image: mongo:6.0
    container_name: lapbee_mongodb_prod
    env_file: '.env.prod'
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD
      MONGO_INITDB_DATABASE: ${MONGO_DATABASE}
    ports:
      - '27017:27017'
    volumes:
      - .data/mongodb_data:/data/db
    restart: always

  # === Redis Service ===
  redis:
    image: redis:6-alpine
    container_name: lapbee_redis_prod
    env_file: '.env.prod'
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    ports:
      - '6379:6379'
    volumes:
      - .data/redis_data:/data
    restart: always

  # === Nginx Service ===
  nginx:
    image: nginx:alpine
    container_name: lapbee_nginx_prod
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      # For Let's Encrypt/Certbot setup, you'd uncomment these and potentially add certbot service
      - ./ssl:/etc/nginx/certs
    ports:
      - '80:80'
      - '443:443'
    depends_on:
      - backend
    restart: always

volumes:
  mongodb_data:
  redis_data:
