# docker-compose.dev.yml
version: '3.8'

services:
  # --------------------
  # MongoDB Database
  # --------------------
  mongodb:
    image: mongo:6
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGO_DATABASE}
    ports:
      - '27017:27017'
    restart: unless-stopped

  # --------------------
  # Redis Cache/Queue
  # --------------------
  redis:
    image: redis:7-alpine
    volumes:
      - redis_data:/data
    ports:
      - '${REDIS_PORT}:6379'
    restart: unless-stopped
# --------------------
# Volumes for data persistence
# --------------------
volumes:
  mongodb_data:
  redis_data:
