export const ErrorInstance = {
  EMAIL_EXIST: 'EMAIL_EXIST_ERROR',
  VALIDATION_REQUEST_BODY: 'VALIDATION_REQUEST_BODY_ERROR',
  VERIFICATION_PENDING_OTP_EXPIRED: 'VERIFICATION_PENDING_OTP_EXPIRED_ERROR',
  EMAIL_ALREADY_PENDING_VERIFICATION: 'EMAIL_ALREADY_PENDING_VERIFICATION_ERROR',
  VERIFIED_NO_PASSWORD: 'VERIFIED_NO_PASSWORD_ERROR',
  PIN_CODE_GONE: 'PIN_CODE_GONE_ERROR',
  PIN_CODE_INVALID: 'PIN_CODE_INVALID_ERROR',
  PIN_CODE_EXPIRED: 'PIN_CODE_EXPIRED_ERROR',
  JWT_TOKEN_INVALID: 'JWT_TOKEN_INVALID',
  JWT_TOKEN_EXPIRED: 'JWT_TOKEN_EXPIRED',
  ACCOUNT_PASSWORD_UPDATED: 'ACCOUNT_PASSWORD_UPDATED',
  PIN_CODE_REQUEST_TOO_SOON: 'PIN_CODE_REQUEST_TOO_SOON_ERROR',
  PIN_CODE_NOTFOUND: 'PIN_CODE_NOTFOUND_ERROR',
  NOTFOUND_EMAIL_SET_PASSWORD_TOKEN: 'NOTFOUND_EMAIL_SET_PASSWORD_TOKEN_ERROR',
  ACCOUNT_LOCKED: 'ACCOUNT_LOCKED_ERROR',
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS_ERROR',
  UNKNOWN: 'UNKNOWN_ERROR',
  RESET_PASSWORD_TOKEN_REQUEST_TOO_SOON: 'RESET_PASSWORD_TOKEN_REQUEST_TOO_SOON_ERROR',
  RESET_PASSWORD_TOKEN_ACCOUNT_PENDING: 'RESET_PASSWORD_TOKEN_ACCOUNT_PENDING',
  NOT_MATCH_ACCOUNT_UPDATE_PASSWORD: 'NOT_MATCH_ACCOUNT_UPDATE_PASSWORD',
  RESET_PASSWORD_TOKEN_NOT_FOUND: 'RESET_PASSWORD_TOKEN_NOT_FOUND_ERROR',
  EMAIL_NOT_EXIST: 'EMAIL_NOT_EXIST_ERROR',
  AUTHORIZATION_HEADER_MISSING: 'AUTHORIZATION_HEADER_MISSING_ERROR'
} as const;

export type ErrorInstanceKeys = keyof typeof ErrorInstance;
export type ErrorInstanceValues = (typeof ErrorInstance)[ErrorInstanceKeys];
